### ISSUE TITLE
Remove DNS resolution of *.local in favor of DOCKSAL_DNS_DOMAIN

### ISSUE THREAD

**Issue by gmta** [docksal/service-dns#2]
Currently `service-dns` resolves all requests to `*.local` to `127.0.0.1`. It would be nice to be able to disable or rename the `.local` DNS zone.

Use case: we use `*.company.local` as an internal DNS zone, which conflicts with this service's configuration. As a workaround, we now build a specific DNS container image where we empty out the configuration file for the `.local` zone.

Suggested fixes:
- Support disabling this zone, e.g. `DNS_LOCAL_ZONE_ENABLED=false`
- Support renaming this zone, e.g. `DNS_LOCAL_ZONE=something-else-entirely`
- Leave out this additional zone since there are valid alternatives such as `.docksal` or `localhost` to connect to other services.

**Comment by gmta** [comment]
By the way, I understand that it's not really a smart idea to use an internal DNS zone ending in `.local` for a multitude of reasons - but it's legacy :-)

**Comment by achekulaev** [comment]
Docksal provides resolution for `.docksal`. What is `.local`?

**Comment by gmta** [comment]
Please look here:
https://github.com/docksal/service-dns/commit/42b64a71c3850dc019b806120ab716fdbb1a8356#diff-b958f585a04af5ee2087610ea7180f34R15

**Comment by achekulaev** [comment]
Whoa!.. @lmakarov do we even need this?

**Comment by lmakarov** [comment]
`.local` was added a while ago to support people with "legacies". Those, that did not want to use `.docksal` and wanted `.local` instead. I don't think this feature was ever advertised, so it may be fine to remove it. Adding to the next release backlog.

**Comment by achekulaev** [comment]
@lmakarov got it. Well `DOCKSAL_DNS_DOMAIN` is configurable for some time now, so those people who need it will be able to use `local`.
