### ISSUE TITLE
Fallback DNS "9.9.9.9" conflicts with upstream DNS

### ISSUE THREAD

**Issue by gmta** [docksal/service-dns#5]
In `bin/fin`'s `install_dns_service` a fallback DNS `9.9.9.9` is provided. However, this does not seem to function as a fallback and instead, dnsmasq seems to take whatever DNS server responds fastest. This breaks setups with VPN or slow(er) internal DNS servers.

Result with `--dns="<my upstream>" --dns="9.9.9.9"` (Docksal default):

```
% nslookup my.internal.site. 192.168.64.100
Server:		192.168.64.100
Address:	192.168.64.100#53

** server can't find my.internal.site: NXDOMAIN
```

Result with `--dns="<my upstream>"` (modified):

```
% nslookup my.internal.site. 192.168.64.100
Server:		192.168.64.100
Address:	192.168.64.100#53

Non-authoritative answer:
my.internal.site	canonical name = other.internal.site.
Name:	other.internal.site.
Address: 10.0.0.1
```

Based on [this Stackoverflow answer](https://unix.stackexchange.com/a/106729), you might want to enable `strict-order` in `dnsmasq.conf` to guarantee that both `DOCKSAL_DNS_UPSTREAM` and the autodetected value from the host's `resolv.conf` are working correctly. By using this option in our custom DNS image, the issue was resolved for us.

**Comment by lmakarov** [comment]
`--dns` is a `docker run` option which writes `nameserver` values `to /etc/resolv.conf` in a container.

From http://man7.org/linux/man-pages/man5/resolv.conf.5.html

> **nameserver** Name server IP address
> ...
> If there are multiple servers, the resolver library queries them in the order listed.
> 

So the order should be already preserved there.

> **timeout:n**
> Sets the amount of time the resolver will wait for a response from a remote name server before retrying the query via a different name server... Measured in seconds, the default is RES_TIMEOUT (currently 5, see <resolv.h>)...
> 

Sounds like you are hitting that 5s timeout before DNS resolver is going to try another server.

Another interesting find - from https://docs.docker.com/config/containers/container-networking/

> --dns
> The IP address of a DNS server. To specify multiple DNS servers, use multiple --dns flags. If the container cannot reach any of the IP addresses you specify, Google’s public DNS server 8.8.8.8 is added, so that your container can resolve internet domains.
> 

This would be the way to go and we could just drop the second `--dns` option, however... it does not seem to work. Doing `--dns="2.2.2.2"` (a non-working DNS server address) results in the container loosing DNS resolution. There is no automatic fallback done by Docker to `8.8.8.8`.

We may have to refactor `docksal/dns` and pass the primary and fallback DNS setting as environment variables and no rely on Docker's `--dns` settings at all.

**Comment by gmta** [comment]
@lmakarov 

> So the order should be already preserved there.

Except, that isn't the case since you use `dnsmasq`:

https://linux.die.net/man/8/dnsmasq

```
-o, --strict-order
    By default, dnsmasq will send queries to any of the upstream servers it knows about and tries
    to favour servers that are known to be up. Setting this flag forces dnsmasq to try each query
    with each server strictly in the order they appear in /etc/resolv.conf 
```

> Sounds like you are hitting that 5s timeout before DNS resolver is going to try another server.

No, the response is immediate.

**Comment by lmakarov** [comment]
@GMTA ok, that makes sense. I see you update the issues description:

> By using this option in our custom DNS image, the issue was resolved for us.

Please submit a PR so you can get a credit for this improvement :)
